%% 1. Load Dataset into MATLAB Datastore
dataFolder = fullfile(pwd, 'data', 'processed', 'combined_train');
imds = imageDatastore(dataFolder, ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

% Split into 80% Training and 20% Validation (stratified)
[imdsTrain, imdsVal] = splitEachLabel(imds, 0.8, 'randomized');

%% 2. Apply Data Augmentation (Crucial for small dataset / Grade 1)
inputSize = [224 224 3]; % Standard input size for ResNet-50

augmenter = imageDataAugmenter( ...
    'RandXReflection', true, ...
    'RandYReflection', true, ...
    'RandRotation', [-180 180], ...
    'RandScale', [0.85 1.15], ...
    'RandXShear', [-10 10], ...
    'RandYShear', [-10 10]);

augTrain = augmentedImageDatastore(inputSize, imdsTrain, 'DataAugmentation', augmenter);
augVal   = augmentedImageDatastore(inputSize, imdsVal);

%% 3. Load Pretrained ResNet-50 & Replace Final Layers
net = resnet50;
lgraph = layerGraph(net);

numClasses = 5;
newFCLayer = fullyConnectedLayer(numClasses, ...
    'Name', 'new_fc', ...
    'WeightLearnRateFactor', 10, ...
    'BiasLearnRateFactor', 10);
newClassLayer = classificationLayer('Name', 'new_classoutput');

lgraph = replaceLayer(lgraph, 'fc1000', newFCLayer);
lgraph = replaceLayer(lgraph, 'ClassificationLayer_fc1000', newClassLayer);

%% 4. Configure Training Options
options = trainingOptions('adam', ...
    'MiniBatchSize', 16, ...
    'MaxEpochs', 15, ...
    'InitialLearnRate', 1e-4, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', augVal, ...
    'ValidationFrequency', 10, ...
    'Verbose', false, ...
    'Plots', 'training-progress', ...
    'ExecutionEnvironment', 'auto'); % Uses NVIDIA GPU if available, else CPU

%% 5. Train the Model
disp('Starting model training...');
trainedDRNet = trainNetwork(augTrain, lgraph, options);

%% 6. Save the Trained Weights
if ~exist('models', 'dir'), mkdir('models'); end
save('models/trainedDRNet.mat', 'trainedDRNet');
disp(' Training complete! Model saved to models/trainedDRNet.mat');